### ISSUE TITLE
Strategy for identifying & resolving outliers needing search update

### ISSUE THREAD

**Issue by DevinSmithWork** [eScholarship/elements-api-tools#4]
### Why 

There are a number of users who need a name search update but aren't getting them because they don't meet Symplectic's criteria for inclusion in the manual update. An Elements administrator cannot easily refresh these groups of users one-off. We therefore  require a programmatic method of identifying them in the HR feed so they may be grouped in Elements so that their searches may be reset.  

### What 

The Reporting DB should be able to surface the information that we need: 

* user prop ID 
* name search settings with ``LastName, Initials``
* name search settings that have been updated (so won't be part of Symplectic's manual update) 
* high pending counts 

This report could be used to identify users to be added to an HR feed override. The HR feed override could add a ``1`` in an unused ``GenericXX`` field to indicate that this user should have their search settings flushed back to default so their name settings can be set to ``LastName, FirstName`` during Symplectic's manual update. 

Our expectation is that after an initial run, a similar scan would only need to be run once every 6 months to a year. We should monitor for the first year to confirm.

**Comment by DevinSmithWork** [comment]
Pulls up users with any "Last, F." in defaults, along with details about which services ("Source ID" and "Source Name") have been modified.

```
select
	usto.[User ID],
	usto.[Override Author],
	usto.[Author Override],
	usto.[Source ID],
	usto.[source Name],
	ustd.[Author] as [Default Author Search Term]
from 
	[User Search Term Overrides] usto
		join [User Search Term Defaults] ustd
			on usto.[User ID] = ustd.[User ID]
			and ustd.[Author] like '%, [\A-Z]"';
```

**Note** The table [User Search Term Overrides] includes a field "Should Run Name Search", which might be used for the flagging mentioned here?

**Comment by alainna** [comment]
@DevinSmithWork apologies, just seeing this question: 

> Note The table [User Search Term Overrides] includes a field "Should Run Name Search", which might be used for the flagging mentioned here?

According to the [Reporting DB Guide](https://support.symplectic.co.uk/support/solutions/articles/6000049726) (latest should be 6.9.0), this refers to whether the user's name-based search will be run for the flagged data source. That probably corresponds to a certain data source being ticked on/off in the user's name based search settings. 

Here's Elements User ID ``15196``'s settings for individual data sources -- 

![image](https://github.com/user-attachments/assets/123024ae-50a4-4577-8318-16980744573c)

**Comment by DevinSmithWork** [comment]
More robust version (now captures "Last, F. M.", with and without trailing periods) with publication counts

```
select
	usto.[User ID],
	u.[Computed Name Alphabetical],
	COUNT(DISTINCT pp.[Publication ID]) as 'Pending Pubs',
	ustd.[Author] as [Default Author Search Term],
	usto.[Override Author],
	usto.[Author Override],
	usto.[Source ID],
	usto.[source Name]
from 
	[User Search Term Overrides] usto
		join [User Search Term Defaults] ustd
			on usto.[User ID] = ustd.[User ID]
			and ustd.[Author] not like '%" OR "%'
			and (ustd.[Author] like '%, [\A-Z]"'
				or ustd.[Author] like '%, [\A-Z] [\A-Z]"'
				or ustd.[Author] like '%, [\A-Z]."'
				or ustd.[Author] like '%, [\A-Z]. [\A-Z]."')
		join [User] u
			on ustd.[User ID] = u.ID
		left join [Pending Publication] pp
			on pp.[User ID] = u.ID
group by
	usto.[User ID],
	u.[Computed Name Alphabetical],
	usto.[Override Author],
	usto.[Author Override],
	usto.[Source ID],
	usto.[source Name],
	ustd.[Author]
order by
	COUNT(DISTINCT pp.[Publication ID]) desc;
```
